apps/chat/urls.py
from django.urls import path

from .views import ChatRoomView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    path(r"<username>/", ChatRoomView.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('apps.chat.urls')),
]

apps/chat/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q


class ChatRoomManager(models.Manager):
    def by_user(self, user):
        filter_user_room = Q(first_user=user) | Q(second_user=user)
        filter_non_self_room = Q(first_user=user) & Q(second_user=user)

        return self.get_queryset().filter(filter_user_room).exclude(filter_non_self_room).distinct()

    def get_or_create(self, first_user, second_user):
        if first_user == second_user:
            return None

        filter_first = Q(first_user=first_user) & Q(second_user=second_user)
        filter_second = Q(first_user=second_user) & Q(second_user=first_user)

        queryset = self.get_queryset().filter(filter_first | filter_second).distinct()
        if queryset.count():
            return queryset.order_by('updated_at').first(), False

        room = self.model(first_user=first_user, second_user=second_user, )
        room.save()

        return room, True


class ChatRoom(models.Model):
    first_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                   related_name='chat_room_first_user')
    second_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                    related_name='chat_room_second_user')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ChatRoomManager()

    @property
    def room_name(self):
        return f'chat-{self.id}'

    # def broadcast(self, message=None):
    #     if message:
    #         broadcast_message_to_chat(message, group_name=self.room_name, user='admin')
    #         return True
    #     return False


class ChatMessage(models.Model):
    chat_room = models.ForeignKey(ChatRoom, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)

apps/chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control"}
        )
    )

apps/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormMixin

from .forms import ComposeForm
from .models import ChatRoom, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'

    def get_queryset(self):
        return ChatRoom.objects.by_user(self.request.user)


class ChatRoomView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/chat_room.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return ChatRoom.objects.by_user(self.request.user)

    def get_object(self, **kwargs):
        target_user = get_object_or_404(User, username=self.kwargs.get("username"))
        chat_room, created = ChatRoom.objects.get_or_create(self.request.user, target_user)
        if not chat_room:
            raise Http404

        return chat_room

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()

        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        form = self.get_form()
        if not form.is_valid():
            self.form_invalid(form)

        chat_room = self.get_object()
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=request.user, chat_room=chat_room, message=message)
        return super().form_valid(form)

    def form_valid(self, form):
        chat_room = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, chat_room=chat_room, message=message)

        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Chat x Channels Rapidly</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class='container'>
    <div class='row border-bottom my-3 py-3'>
        <div class='col'>
            <h1 class='p-0 m-0'>Chat x Channels Rapidly</h1>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</div>


{% block script %}
{% endblock %}

</body>
</html>

templates/chat/chat_room.html
{% extends "base.html" %}

{% block content %}
    <h3>Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
    <ul id='chat-items'>
        {% for chat in object.chatmessage_set.all %}

            <li>{{ chat.message }} via {{ chat.user }}</li>

        {% endfor %}
    </ul>

    <form id='form' method='POST'> {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" id="myUsername" value="{{ user.username }}"/>
        <input type='submit' class='btn btn-primary'/>
    </form>

{% endblock %}

{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
    <script>
        let endpoint = 'ws://' + window.location.host + '/ws' + window.location.pathname;
        let socket = new ReconnectingWebSocket(endpoint);
        let form = $('#form');
        let chatHolder = $('#chat-items')
        let me = $('myUsername').val()
        socket.onmessage = function (e) {
            console.log('message', e)
            const response = JSON.parse(e.data)
            if (e.data !== null) {
                chatHolder.append('<li>' + response.message + ' via ' + response.username + '</li>')
            }

        }

        socket.onopen = function (e) {
            form.submit(function (event) {
                event.preventDefault()

                const message = $('#id_message').val()
                const messageJson = JSON.stringify({message: message, me: me})

                socket.send(messageJson);
                form[0].reset()
            })
        }

        socket.onerror = function (e) {
            console.log('error', e)
        }

        socket.onclose = function (e) {
            console.log('close', e)
        }

    </script>
{% endblock %}

templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}


{% endblock %}